### PR TITLE
Added ability to show the urls of the exposed services to the proxy plugin.

### PR DESCRIPTION
**Pull request by sepal**
This pull request shows the user the urls to the services, since it might not be always obvious for every user how they are named.

### CODE REVIEW

**Comment by pmelab** [comment]
Good point, displaying urls makes things easier.
`preprocess_config` is always called initially, so this should be fine. Some other suggestions.
1. `cleanup` is always executed and should not print output. `initialized_networks` is a better place to do that.
2. the plugins already provide a logger instance. we should use that instead of print.
3. the `hosts` member already collects domain information for use during network initialization. perhaps we can merge `hosts` with `domains`

**Comment by sepal** [comment]
1: I think the urls should be last thing dork-compose outputs, or at least at the end of initializing the containers. If you move the url output to the `initialized_networks` function, then it will drown in the stream of ouput, since the docker-compose after the `initialized_networks` was called. `show_urls` is how I tell clean_up when to print the urls. Maybe we can find a better solution though...

2: Good point will change that.

3: Oh yeah I missed that, we should definitely use that instead of adding a new property.

**Comment by pmelab** [comment]
You are mentioning github users 1, 2 and 3 :)

We could introduce an "info" command where plugins can publish information. Could also help for snapshot locations, actual values for project and instance and similar.

**Comment by sepal** [comment]
oops sorry...

Yeah, that would probably the best solution

**Comment by pmelab** [comment]
I added the `info` command in the latest push to master.

**Comment by pmelab** [comment]
Feature implemented in master, using "dork-compose info" command.

**Pull request closed without merging**
